[12.0][MIG] connector ecommerce
OCA/connector-ecommerce pull request #49
Opened 2019-03-20 10:04 UTC by acm1pt-colorado

2019-03-20 10:29 UTC, pedrobaeza commented
Please check Runbot status

2019-04-24 08:49 UTC, sebalix commented on connector_ecommerce/views/sale_view.xml
> +                    groups="base.group_sale_manager" />
```suggestion
                    groups="sales_team.group_sale_manager" />
```

2019-05-10 14:19 UTC, ivantodorovich requested changes

2019-05-10 14:19 UTC, ivantodorovich commented on connector_ecommerce/tests/test_picking_event.py
> +            'product_uom': self.env.ref('product.product_uom_unit').id,
```suggestion
            'product_uom': self.env.ref('uom.product_uom_unit').id,
```

2019-05-10 14:19 UTC, ivantodorovich commented on connector_ecommerce/tests/test_picking_event.py
> +            'product_uom': self.env.ref('product.product_uom_unit').id,
```suggestion
            'product_uom': self.env.ref('uom.product_uom_unit').id,
```

2019-09-09 12:00 UTC, mlaitinen commented
Update to the description: https://github.com/OCA/sale-workflow/pull/812 was closed because another PR containing the migrated `sale_exception` was merged at https://github.com/OCA/sale-workflow/pull/831. So that has been taken care of.

2019-09-10 15:51 UTC, mlaitinen commented
@acm1pt-colorado Both of the PR's mentioned in the description are now merged.

2019-09-26 12:59 UTC, ivantodorovich commented
@acm1pt-colorado can you please force travis/runbots to rerun?
both prs are merged now

2019-10-14 07:54 UTC, sebalix approved these changes

2019-10-14 08:10 UTC, ivantodorovich commented
runbot is giving warnings:
```
2019-10-09 16:32:54,648 172 WARNING openerp_test odoo.models: exception.rule.create() with unknown fields: rule_group
2019-10-09 16:32:54,653 172 WARNING openerp_test odoo.models: exception.rule.create() with unknown fields: rule_group
2019-10-09 16:32:54,657 172 WARNING openerp_test odoo.models: exception.rule.create() with unknown fields: rule_group
```

`rule_group` was removed here: https://github.com/OCA/server-tools/commit/254391987cea07e93c668399ee1c6d51d8491fb2#diff-c7fd995df65e10a635951020066e82a6

2019-10-15 11:22 UTC, ivantodorovich commented
@acm1pt-colorado looks like that last commit is authored by someone that hasn't signed the CLA
can you please sign it, or amend that last commit?

Besides that, everything looks good to me! :+1:  !

2019-10-15 11:23 UTC, ivantodorovich approved these changes
:+1: 

besides CLA, everything else LGTM

2019-10-15 11:23 UTC, acm1pt-colorado commented
Thanks @ivantodorovich 

Im tried to see the error from runbot but im not able to saw the logs.

2019-10-15 11:26 UTC, ivantodorovich commented
> Thanks @ivantodorovich
> 
> Im tried to see the error from runbot but im not able to saw the logs.

Hmmm. You fixed it here: https://github.com/OCA/connector-ecommerce/pull/49/commits/d515cdf3ffed143fb025fea46a747cc4800125fd

There's no more error :+1:

2019-10-15 11:28 UTC, ivantodorovich commented
@acm1pt-colorado the only thing missing is this:

> Hey @acm1pt-colorado, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet.
> You can read and sign our full Contributor License Agreement here: http://odoo-community.org/page/cla
> Here is a list of the users:
> 
> * LuisAdan [luis.jimenez@pesol.es](mailto:luis.jimenez@pesol.es) (no github login found)
> 
> Appreciation of efforts,
> OCA CLAbot

2019-10-15 11:30 UTC, guewen commented
@acm1pt-colorado thanks for your work, can you confirm that you signed the CLA?

2019-10-15 11:52 UTC, acm1pt-colorado commented
Hi @guewen @ivantodorovich 

I did with the user acm1pt-colorado but i dont know why is asking me again.

![image](https://user-images.githubusercontent.com/14888212/66829100-e9c6fe00-ef52-11e9-8b11-998fc1e8829c.png)

2019-10-15 11:59 UTC, guewen commented
@acm1pt-colorado thanks, I checked in the odoo-community DB and I found your account with the ICLA tag.

/ocabot merge

2019-10-15 12:25 UTC, ivantodorovich commented
Thanks for the hard work @acm1pt-colorado !!! :)

2019-10-15 12:29 UTC, merged